using EnvDTE;
using Microsoft.VisualStudio.Shell;
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Task = System.Threading.Tasks.Task;

namespace PolarisTools.Event.Language
{
    /// <summary>
    /// 阶段5 §8 的"旧 .cmd 迁移器"：扫一份底层 CMD，从 <c>TALKER raw pos</c>/<c>PIC raw pose</c>
    /// 行里抠出出现过的角色 raw 码和姿势 raw 串，写一份别名候选 yaml。因为 raw 码本身不带人类可读名字，
    /// 候选文件里的 key 只能用 <c>Actor_&lt;raw&gt;</c>/<c>Pose_&lt;n&gt;</c> 占位，作者需要手动把这些
    /// 改成好记的名字——迁移器负责"找出重复出现的组合"，不负责"猜出角色叫什么"。
    /// </summary>
    internal sealed class HppMigrateCommand
    {
        public const int CommandId = 0x0104;
        public static readonly Guid CommandSet = new Guid("1ba8fc7a-877c-43a5-8937-e1ed1b2dacea");

        static readonly Regex TalkerLine = new Regex(@"^TALKER\s+(\S+)\s+(\S+)\s*$", RegexOptions.Compiled | RegexOptions.Multiline);
        static readonly Regex PicLine = new Regex(@"^PIC\s+(\S+)\s+(\S+)\s*$", RegexOptions.Compiled | RegexOptions.Multiline);

        readonly AsyncPackage package;

        HppMigrateCommand(AsyncPackage package, OleMenuCommandService commandService)
        {
            this.package = package;
            commandService.AddCommand(new MenuCommand(Execute, new CommandID(CommandSet, CommandId)));
        }

        public static async Task InitializeAsync(AsyncPackage package)
        {
            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(package.DisposalToken);
            var commandService = await package.GetServiceAsync(typeof(IMenuCommandService)) as OleMenuCommandService;
            new HppMigrateCommand(package, commandService);
        }

        void Execute(object sender, EventArgs e)
        {
            ThreadHelper.ThrowIfNotOnUIThread();

            if (!(package.GetServiceAsync(typeof(DTE)).GetAwaiter().GetResult() is DTE dte) || dte.ActiveDocument == null)
            {
                HppOutputPane.WriteLine("[PolarisEvent] No active document.");
                return;
            }

            string filePath = dte.ActiveDocument.FullName;
            if (!filePath.EndsWith(".cmd", StringComparison.OrdinalIgnoreCase))
            {
                HppOutputPane.WriteLine("[PolarisEvent] Active document is not a .cmd file.");
                return;
            }

            string text = File.ReadAllText(filePath);
            var posesByActor = new Dictionary<string, List<string>>(StringComparer.Ordinal);

            foreach (Match m in TalkerLine.Matches(text))
            {
                EnsureActor(posesByActor, m.Groups[1].Value);
            }

            foreach (Match m in PicLine.Matches(text))
            {
                var poses = EnsureActor(posesByActor, m.Groups[1].Value);
                string pose = m.Groups[2].Value;
                if (!poses.Contains(pose))
                {
                    poses.Add(pose);
                }
            }

            if (posesByActor.Count == 0)
            {
                HppOutputPane.WriteLine("[PolarisEvent] No TALKER/PIC lines found; nothing to migrate.");
                return;
            }

            string outputPath = Path.Combine(
                Path.GetDirectoryName(filePath) ?? ".",
                Path.GetFileNameWithoutExtension(filePath) + ".candidate.events.yaml");

            File.WriteAllText(outputPath, BuildYaml(posesByActor));

            HppOutputPane.WriteLine($"[PolarisEvent] Found {posesByActor.Count} distinct raw actor code(s) in {filePath}.");
            HppOutputPane.WriteLine($"[PolarisEvent] Wrote alias candidates to {outputPath}. Rename the Actor_*/Pose_* placeholders before use.");

            dte.ItemOperations.OpenFile(outputPath);
        }

        static List<string> EnsureActor(Dictionary<string, List<string>> map, string raw)
        {
            if (!map.TryGetValue(raw, out var poses))
            {
                poses = new List<string>();
                map[raw] = poses;
            }

            return poses;
        }

        static string BuildYaml(Dictionary<string, List<string>> posesByActor)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Auto-generated by PolarisTools \"Generate Alias Candidates from Active .cmd\".");
            sb.AppendLine("# Rename Actor_*/Pose_* to real names before merging into polaris.events.yaml.");
            sb.AppendLine("actors:");

            foreach (var kv in posesByActor.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                string actorKey = "Actor_" + Sanitize(kv.Key);
                sb.AppendLine($"  {actorKey}:");
                sb.AppendLine($"    raw: {kv.Key}");
                if (kv.Value.Count == 0)
                {
                    sb.AppendLine("    poses: {}");
                    continue;
                }

                sb.AppendLine("    poses:");
                int i = 0;
                foreach (var pose in kv.Value)
                {
                    sb.AppendLine($"      Pose_{i++}: {pose}");
                }
            }

            return sb.ToString();
        }

        static string Sanitize(string raw) => Regex.Replace(raw, "[^A-Za-z0-9]", "_");
    }
}
