using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using Polaris.Particles;
using PolarisTools.Pui;

namespace PolarisTools.Particles.Generation;

[ComVisible(true)]
[Guid("7d590d4c-1867-4d65-a9d7-7c3e888b6d86")]
[ClassInterface(ClassInterfaceType.None)]
public sealed class PolarisPEffectGenerator : IVsSingleFileGenerator
{
    public const string GeneratorName = "PolarisPEffectGenerator";

    public int DefaultExtension(out string pbstrDefaultExtension)
    {
        pbstrDefaultExtension = ".g.cs";
        return VSConstants.S_OK;
    }

    public int Generate(
        string wszInputFilePath,
        string bstrInputFileContents,
        string wszDefaultNamespace,
        IntPtr[] rgbOutputFileContents,
        out uint pcbOutput,
        IVsGeneratorProgress pGenerateProgress)
    {
        ThreadHelper.ThrowIfNotOnUIThread();
        pcbOutput = 0;

        try
        {
            string generated = Build(wszInputFilePath, bstrInputFileContents, wszDefaultNamespace);
            byte[] bytes = Encoding.UTF8.GetBytes(generated);
            IntPtr buffer = Marshal.AllocCoTaskMem(bytes.Length);
            Marshal.Copy(bytes, 0, buffer, bytes.Length);
            rgbOutputFileContents[0] = buffer;
            pcbOutput = (uint)bytes.Length;
            return VSConstants.S_OK;
        }
        catch (Exception ex)
        {
            pGenerateProgress?.GeneratorError(0, 0, ex.Message, 0, 0);
            return VSConstants.E_FAIL;
        }
    }

    internal static string Build(string inputFilePath, string inputFileContents, string defaultNamespace)
    {
        string className = CSharpLiteral.SanitizeIdentifier(Path.GetFileNameWithoutExtension(inputFilePath));
        string namespaceName = string.IsNullOrWhiteSpace(defaultNamespace)
            ? "Polaris.Generated"
            : defaultNamespace;
        PEffectOutline outline = PEffectSyntax.Parse(inputFileContents, Path.GetFileName(inputFilePath));

        var particles = new StringBuilder();
        var timelines = new StringBuilder();
        var attackGhosts = new StringBuilder();
        var particleNames = new HashSet<string>(StringComparer.Ordinal);
        var timelineNames = new HashSet<string>(StringComparer.Ordinal);
        var attackGhostNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (PEffectSection section in outline.Sections)
        {
            switch (section.Kind)
            {
                case PEffectSectionKind.Timeline:
                    EmitField(timelines, timelineNames, "TimelineKey", section.Key);
                    break;
                case PEffectSectionKind.AttackGhost:
                    EmitField(attackGhosts, attackGhostNames, "AttackGhostKey", section.Key);
                    break;
                default:
                    EmitField(particles, particleNames, "ParticleKey", section.Key);
                    break;
            }
        }

        return
            "// <auto-generated />\r\n" +
            "// Generated by PolarisPEffectGenerator from " + Path.GetFileName(inputFilePath) + ".\r\n\r\n" +
            "namespace " + namespaceName + "\r\n" +
            "{\r\n" +
            "    internal static class " + className + "\r\n" +
            "    {\r\n" +
            EmitGroup("Particles", particles) +
            EmitGroup("Timelines", timelines) +
            EmitGroup("AttackGhosts", attackGhosts) +
            "    }\r\n" +
            "}\r\n";
    }

    private static void EmitField(StringBuilder output, ISet<string> usedNames, string keyType, string key)
    {
        string name = CSharpLiteral.SanitizeIdentifier(key);
        if (!usedNames.Add(name))
            return;

        output.Append("            public static readonly global::Polaris.Particles.Effects.")
            .Append(keyType).Append(' ').Append(name)
            .Append(" = new global::Polaris.Particles.Effects.").Append(keyType)
            .Append("(\"").Append(CSharpLiteral.Escape(key)).Append("\");\r\n");
    }

    private static string EmitGroup(string name, StringBuilder fields) =>
        "        internal static class " + name + "\r\n" +
        "        {\r\n" + fields +
        "        }\r\n\r\n";
}
