using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using Polaris.Map.Authoring;
using PolarisTools.Pui;

namespace PolarisTools.Map.Generation;

[ComVisible(true)]
[Guid("53D9F0DC-E87A-4A29-917E-A61DAB1832E1")]
[ClassInterface(ClassInterfaceType.None)]
public sealed class PolarisPmapGenerator : IVsSingleFileGenerator
{
    public const string GeneratorName = "PolarisPmapGenerator";

    public int DefaultExtension(out string extension)
    {
        extension = ".g.cs";
        return VSConstants.S_OK;
    }

    public int Generate(string inputPath, string inputContents, string defaultNamespace,
        IntPtr[] outputContents, out uint outputSize, IVsGeneratorProgress progress)
    {
        ThreadHelper.ThrowIfNotOnUIThread();
        outputSize = 0;
        try
        {
            byte[] bytes = Encoding.UTF8.GetBytes(Build(inputPath, inputContents, defaultNamespace));
            IntPtr buffer = Marshal.AllocCoTaskMem(bytes.Length);
            Marshal.Copy(bytes, 0, buffer, bytes.Length);
            outputContents[0] = buffer;
            outputSize = (uint)bytes.Length;
            return VSConstants.S_OK;
        }
        catch (Exception ex)
        {
            progress?.GeneratorError(0, 0, ex.Message, 0, 0);
            return VSConstants.E_FAIL;
        }
    }

    internal static string Build(string inputPath, string inputContents, string defaultNamespace)
    {
        PmapDocument.Parse(inputContents, Path.GetFileName(inputPath));
        string className = CSharpLiteral.SanitizeIdentifier(Path.GetFileNameWithoutExtension(inputPath));
        string ns = string.IsNullOrWhiteSpace(defaultNamespace) ? "Polaris.Generated" : defaultNamespace;
        string payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(inputContents));
        string sourceName = CSharpLiteral.Escape(Path.GetFileName(inputPath));

        return "// <auto-generated />\r\n" +
               "namespace " + ns + "\r\n{\r\n" +
               "    internal static class " + className + "\r\n    {\r\n" +
               "        private const string Payload = \"" + payload + "\";\r\n\r\n" +
               "        public static string Xml => global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String(Payload));\r\n\r\n" +
               "        public static global::Polaris.Map.MapTransition Enter(global::System.Type pluginType)\r\n" +
               "            => global::Polaris.Map.MapAPI.LoadAndEnterPmap(Xml, pluginType, \"" + sourceName + "\");\r\n" +
               "    }\r\n}\r\n";
    }
}
