using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using Polaris.Pevt.Commands;
using Polaris.Pevt.Diagnostics;
using Polaris.Pevt.Loading;
using Polaris.Pevt.Text;
using PolarisTools.Pui;

namespace PolarisTools.Event.Pevt;

/// <summary>
/// <c>.pevt</c> → C# 单文件生成器。
///
/// 生成的类只做一件事：把压缩后的原始源文本交给运行时。它不包含 AST、不包含 CMD 文本，
/// 也不复制任何解析规则——静态校验和载荷编码全部调用共享的 PolarisEvent 前端
/// （<see cref="PevtSourceCompiler"/> 与 <see cref="PevtEmbeddedSource"/>），因此工具侧和游戏侧
/// 对同一份源码必然得到一致的 AST、绑定结果和 PEVTxxxx。
///
/// 静态错误不会被生成器吞掉：有 Error 级诊断时不产出注册器，只把诊断写进错误列表，
/// 免得一份编译不过的事件被悄悄打进程序集、留到游戏启动时才炸。
/// </summary>
// 独立 GUID：不能和其它生成器共用。
[ComVisible(true)]
[Guid("2b7c4d19-6e83-4a51-9f0d-3c5a8e2b7d41")]
[ClassInterface(ClassInterfaceType.None)]
public sealed class PolarisPevtGenerator : IVsSingleFileGenerator
{
    public const string GeneratorName = "PolarisPevtGenerator";

    /// <summary>Base64 载荷切成多个常量片段，避免单个字面量过长；拼接后必须与单一载荷一致。</summary>
    private const int PayloadChunkLength = 1024;

    public int DefaultExtension(out string pbstrDefaultExtension)
    {
        // Foo.pevt -> Foo.g.cs
        pbstrDefaultExtension = ".g.cs";
        return VSConstants.S_OK;
    }

    public int Generate(
        string wszInputFilePath,
        string bstrInputFileContents,
        string wszDefaultNamespace,
        IntPtr[] rgbOutputFileContents,
        out uint pcbOutput,
        IVsGeneratorProgress pGenerateProgress)
    {
        ThreadHelper.ThrowIfNotOnUIThread();
        pcbOutput = 0;

        try
        {
            string generatedCode = GenerateCSharp(wszInputFilePath, bstrInputFileContents, wszDefaultNamespace, pGenerateProgress);

            byte[] bytes = Encoding.UTF8.GetBytes(generatedCode);
            IntPtr outputBuffer = Marshal.AllocCoTaskMem(bytes.Length);
            Marshal.Copy(bytes, 0, outputBuffer, bytes.Length);

            rgbOutputFileContents[0] = outputBuffer;
            pcbOutput = (uint)bytes.Length;
            return VSConstants.S_OK;
        }
        catch (Exception ex)
        {
            pGenerateProgress?.GeneratorError(0, 0, ex.Message, 0, 0);
            return VSConstants.E_FAIL;
        }
    }

    internal static string ComputeClassName(string inputFilePath)
        => CSharpLiteral.SanitizeIdentifier(Path.GetFileNameWithoutExtension(inputFilePath));

    internal static string ResolveNamespace(string defaultNamespace)
        => string.IsNullOrWhiteSpace(defaultNamespace) ? "Polaris.Generated" : defaultNamespace;

    private static string GenerateCSharp(
        string inputFilePath,
        string inputFileContents,
        string defaultNamespace,
        IVsGeneratorProgress progress)
    {
        string className = ComputeClassName(inputFilePath);
        string ns = ResolveNamespace(defaultNamespace);
        string sourcePath = PevtProjectPaths.ToProjectRelative(inputFilePath);

        // 以磁盘上的原始字节为准，保留源文本里现有的 CRLF 或 LF，不做换行标准化。
        byte[] utf8 = PevtProjectPaths.ReadAllBytesOrEncode(inputFilePath, inputFileContents);

        SourceTextLoadResult loaded = SourceText.FromUtf8(utf8, sourcePath);
        if (!loaded.Success)
        {
            ReportDiagnostics(progress, loaded.Diagnostics);
            return EmptyResult(className, ns, inputFilePath, "源文件不是合法的 UTF-8 文本。");
        }

        PevtCompilation compilation = PevtSourceCompiler.Compile(
            loaded.Text, CommandDescriptorCatalog.Builtin.ToBuiltinApiTable());

        ReportDiagnostics(progress, compilation.Diagnostics);

        if (!compilation.Success)
            return EmptyResult(className, ns, inputFilePath, "源文件存在静态错误，未生成注册器。");

        string declaredId = compilation.Definition.EventId;

        // 同项目内重复事件 ID 在生成期就报，不留到运行时才发现。
        string duplicate = PevtProjectIdIndex.ForFile(inputFilePath).FindDuplicateEventSource(declaredId, inputFilePath);
        if (duplicate != null)
        {
            progress?.GeneratorError(0, 0, $"事件 ID `{declaredId}` 与同项目的 `{duplicate}` 重复。", 0, 0);
            return EmptyResult(className, ns, inputFilePath, $"事件 ID `{declaredId}` 在同项目内重复。");
        }

        PevtEmbeddedSource package = PevtEmbeddedSource.CreateFromBytes(declaredId, sourcePath, utf8);

        return $$"""
            // <auto-generated />
            // Generated by polaris source code generator from {{Path.GetFileName(inputFilePath)}}
            //
            // 载荷是压缩后的原始 PEVT 源文本，不是字节码，也不是原版命令文本。
            // 游戏侧仍会重新解压、校验哈希并执行完整静态校验，不信任本文件里的任何结论。

            namespace {{ns}}
            {
                [global::Polaris.Pevt.Registration.PevtAutoRegistration]
                public sealed class {{className}}_PevtRegistrar : global::Polaris.Pevt.Registration.IPevtRegistrar
                {
            {{EmitPayloadConstants(package.Payload)}}
                    public void Register(global::Polaris.Pevt.Registration.PevtRegistrationContext context)
                    {
                        context.Register(new global::Polaris.Pevt.Loading.PevtEmbeddedSource(
                            formatVersion: {{package.FormatVersion}},
                            compression: "{{CSharpLiteral.Escape(package.Compression)}}",
                            declaredId: "{{CSharpLiteral.Escape(package.DeclaredId)}}",
                            sourcePath: "{{CSharpLiteral.Escape(package.SourcePath)}}",
                            uncompressedLength: {{package.UncompressedLength}},
                            contentHash: "{{package.ContentHash}}",
                            payload: {{PayloadExpression(package.Payload)}}));
                    }
                }
            }
            """;
    }

    /// <summary>把 Base64 载荷切成多个 <c>private const string</c>。</summary>
    private static string EmitPayloadConstants(string payload)
    {
        var builder = new StringBuilder();
        int index = 0;

        for (int offset = 0; offset < payload.Length; offset += PayloadChunkLength, index++)
        {
            string chunk = payload.Substring(offset, Math.Min(PayloadChunkLength, payload.Length - offset));
            builder.Append("        private const string Payload").Append(index)
                .Append(" = \"").Append(chunk).Append("\";\n");
        }

        if (index == 0)
            builder.Append("        private const string Payload0 = \"\";\n");

        return builder.ToString();
    }

    private static string PayloadExpression(string payload)
    {
        int count = Math.Max(1, (payload.Length + PayloadChunkLength - 1) / PayloadChunkLength);
        return string.Join(" + ", Enumerable.Range(0, count).Select(i => "Payload" + i));
    }

    /// <summary>
    /// 静态错误时产出一个不注册任何东西的空类。保留类本身是为了让引用它的代码不至于跟着报错，
    /// 真正的原因已经进了错误列表。
    /// </summary>
    private static string EmptyResult(string className, string ns, string inputFilePath, string reason) =>
        $$"""
        // <auto-generated />
        // Generated by polaris source code generator from {{Path.GetFileName(inputFilePath)}}
        //
        // {{reason}}

        namespace {{ns}}
        {
            internal static class {{className}}_PevtNotGenerated
            {
                public const string Reason = "{{CSharpLiteral.Escape(reason)}}";
            }
        }
        """;

    private static void ReportDiagnostics(IVsGeneratorProgress progress, IReadOnlyList<Diagnostic> diagnostics)
    {
        if (progress == null)
            return;

        foreach (Diagnostic diagnostic in diagnostics)
        {
            // 错误列表的行列是 0 起始，PEVT 诊断是 1 起始。
            uint line = diagnostic.Location != null ? (uint)Math.Max(0, diagnostic.Location.StartLine - 1) : 0;
            uint column = diagnostic.Location != null ? (uint)Math.Max(0, diagnostic.Location.StartColumn - 1) : 0;
            string message = $"{diagnostic.Id}: {diagnostic.Message}";

            if (diagnostic.Severity == DiagnosticSeverity.Error)
                progress.GeneratorError(0, 0, message, line, column);
            else
                progress.GeneratorError(1, 0, message, line, column);
        }
    }
}
