using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using Polaris.Pevt.Actors;
using Polaris.Pevt.Diagnostics;
using PolarisTools.Event.Pevt;
using PolarisTools.Pui;

namespace PolarisTools.Event.Actors;

/// <summary>
/// <c>.pactorx</c>（PEVT-E06 人物目录增量扩展 sidecar）→ C# 单文件生成器。
///
/// 生成的类只提交一份已校验的不可变 <see cref="ActorCatalogExtension"/>：没有 XML 解析器，
/// 不加载文件，也不生成 PEVT 源码——读取和校验全部调用共享的 <see cref="ActorCatalogReader.ReadExtension"/>，
/// 因此工具侧与游戏侧对同一份 sidecar 必然得到相同的判定和相同的 PEVT91xx。
///
/// 扩展的目标人物可能来自别的程序集，工具侧不做跨程序集的目标存在性检查——那是运行时目录合并
/// 的职责（<c>ActorDirectoryBuilder.ApplyExtensions</c>），提前在这里假装能判断只会造出误报。
/// </summary>
[ComVisible(true)]
[Guid("2c9e6a4f-7b1d-4e6a-9c3f-1a8d5f0b6e27")]
[ClassInterface(ClassInterfaceType.None)]
public sealed class PolarisPactorExtensionGenerator : IVsSingleFileGenerator
{
    public const string GeneratorName = "PolarisPactorExtensionGenerator";

    public int DefaultExtension(out string pbstrDefaultExtension)
    {
        pbstrDefaultExtension = ".g.cs";
        return VSConstants.S_OK;
    }

    public int Generate(
        string wszInputFilePath,
        string bstrInputFileContents,
        string wszDefaultNamespace,
        IntPtr[] rgbOutputFileContents,
        out uint pcbOutput,
        IVsGeneratorProgress pGenerateProgress)
    {
        ThreadHelper.ThrowIfNotOnUIThread();
        pcbOutput = 0;

        try
        {
            string generatedCode = GenerateCSharp(wszInputFilePath, bstrInputFileContents, wszDefaultNamespace, pGenerateProgress);

            byte[] bytes = Encoding.UTF8.GetBytes(generatedCode);
            IntPtr outputBuffer = Marshal.AllocCoTaskMem(bytes.Length);
            Marshal.Copy(bytes, 0, outputBuffer, bytes.Length);

            rgbOutputFileContents[0] = outputBuffer;
            pcbOutput = (uint)bytes.Length;
            return VSConstants.S_OK;
        }
        catch (Exception ex)
        {
            pGenerateProgress?.GeneratorError(0, 0, ex.Message, 0, 0);
            return VSConstants.E_FAIL;
        }
    }

    private static string GenerateCSharp(
        string inputFilePath,
        string inputFileContents,
        string defaultNamespace,
        IVsGeneratorProgress progress)
    {
        string className = PolarisPactorGenerator.ComputeClassName(inputFilePath);
        string ns = PolarisPactorGenerator.ResolveNamespace(defaultNamespace);
        string sourcePath = PevtProjectPaths.ToProjectRelative(inputFilePath);

        byte[] utf8 = PevtProjectPaths.ReadAllBytesOrEncode(inputFilePath, inputFileContents);

        ActorCatalogExtensionReadResult result = ActorCatalogReader.ReadExtension(utf8, sourcePath);
        ReportDiagnostics(progress, result.Diagnostics);

        if (!result.Success)
            return EmptyResult(className, ns, inputFilePath, "`.pactorx` 存在静态错误，未生成注册器。");

        ActorCatalogExtension extension = result.Extension;
        string sourceHash = Polaris.Pevt.Loading.PevtEmbeddedSource.ComputeContentHash(utf8);

        return $$"""
            // <auto-generated />
            // Generated by polaris source code generator from {{Path.GetFileName(inputFilePath)}}
            //
            // 只包含一份已校验的不可变人物目录扩展（PEVT-E06）：没有 XML 解析器，不加载文件，
            // 也不生成 PEVT 源码。扩展目标是否存在由游戏侧目录合并时判定，这里不提前假装知道。

            namespace {{ns}}
            {
                [global::Polaris.Pevt.Registration.PevtActorAutoRegistration]
                public sealed class {{className}}_PevtActorExtensionRegistrar : global::Polaris.Pevt.Registration.IPevtActorRegistrar
                {
                    public void Register(global::Polaris.Pevt.Registration.PevtActorRegistrationContext context)
                    {
                        context.RegisterExtension(BuildExtension(), "{{sourceHash}}");
                    }

                    private static global::Polaris.Pevt.Actors.ActorCatalogExtension BuildExtension() =>
                        new global::Polaris.Pevt.Actors.ActorCatalogExtension(
                            {{extension.Version}},
                            "{{CSharpLiteral.Escape(extension.SourcePath)}}",
                            new global::Polaris.Pevt.Actors.ActorExtensionDefinition[]
                            {
            {{EmitExtensions(extension)}}                });
                }
            }
            """;
    }

    private static string EmitExtensions(ActorCatalogExtension extension)
    {
        var builder = new StringBuilder();

        foreach (ActorExtensionDefinition definition in extension.Extensions)
        {
            builder.Append("                    new global::Polaris.Pevt.Actors.ActorExtensionDefinition(\n")
                .Append("                        \"").Append(CSharpLiteral.Escape(definition.ActorId)).Append("\",\n")
                .Append("                        ").Append(AppearanceArray(definition)).Append("),\n");
        }

        return builder.ToString();
    }

    private static string AppearanceArray(ActorExtensionDefinition definition)
    {
        var parts = new StringBuilder("new global::Polaris.Pevt.Actors.ActorAppearance[] { ");

        bool first = true;
        foreach (ActorAppearance appearance in definition.Appearances)
        {
            if (!first)
                parts.Append(", ");
            first = false;

            parts.Append("new global::Polaris.Pevt.Actors.ActorAppearance(\"")
                .Append(CSharpLiteral.Escape(appearance.Id)).Append("\", \"")
                .Append(CSharpLiteral.Escape(appearance.PortraitId)).Append("\", \"")
                .Append(CSharpLiteral.Escape(appearance.Pose)).Append("\", \"")
                .Append(CSharpLiteral.Escape(appearance.Frame)).Append("\")");
        }

        parts.Append(" }");
        return parts.ToString();
    }

    private static string EmptyResult(string className, string ns, string inputFilePath, string reason) =>
        $$"""
        // <auto-generated />
        // Generated by polaris source code generator from {{Path.GetFileName(inputFilePath)}}
        //
        // {{reason}}

        namespace {{ns}}
        {
            internal static class {{className}}_PevtActorExtensionNotGenerated
            {
                public const string Reason = "{{CSharpLiteral.Escape(reason)}}";
            }
        }
        """;

    private static void ReportDiagnostics(IVsGeneratorProgress progress, System.Collections.Generic.IReadOnlyList<Diagnostic> diagnostics)
    {
        if (progress == null)
            return;

        foreach (Diagnostic diagnostic in diagnostics)
        {
            uint line = diagnostic.Location != null ? (uint)Math.Max(0, diagnostic.Location.StartLine - 1) : 0;
            uint column = diagnostic.Location != null ? (uint)Math.Max(0, diagnostic.Location.StartColumn - 1) : 0;
            string message = $"{diagnostic.Id}: {diagnostic.Message}";

            if (diagnostic.Severity == DiagnosticSeverity.Error)
                progress.GeneratorError(0, 0, message, line, column);
            else
                progress.GeneratorError(1, 0, message, line, column);
        }
    }
}
