using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using Polaris.AI.Authoring;
using PolarisTools.Pui;
using PolarisTools.Res;

namespace PolarisTools.AI.Npc;

[ComVisible(true)]
[Guid("8F938C61-46B2-4E4E-A5C8-BDB973FF2411")]
[ClassInterface(ClassInterfaceType.None)]
public sealed class PolarisPnpcGenerator : IVsSingleFileGenerator
{
    public const string GeneratorName = "PolarisPnpcGenerator";

    public int DefaultExtension(out string extension) { extension = ".g.cs"; return VSConstants.S_OK; }

    public int Generate(string inputPath, string inputContents, string defaultNamespace,
        IntPtr[] outputContents, out uint outputSize, IVsGeneratorProgress progress)
    {
        ThreadHelper.ThrowIfNotOnUIThread();
        outputSize = 0;
        try
        {
            byte[] bytes = Encoding.UTF8.GetBytes(Build(inputPath, inputContents, defaultNamespace));
            IntPtr buffer = Marshal.AllocCoTaskMem(bytes.Length);
            Marshal.Copy(bytes, 0, buffer, bytes.Length);
            outputContents[0] = buffer;
            outputSize = (uint)bytes.Length;
            return VSConstants.S_OK;
        }
        catch (Exception ex)
        {
            progress?.GeneratorError(0, 0, ex.Message, 0, 0);
            return VSConstants.E_FAIL;
        }
    }

    internal static string Build(string inputPath, string inputContents, string defaultNamespace)
    {
        ThreadHelper.ThrowIfNotOnUIThread();
        PnpcDocument document = PnpcXml.Parse(inputContents);
        PnpcDiagnostic[] diagnostics = PnpcXml.Validate(document).ToArray();
        if (diagnostics.Length != 0) throw new FormatException(string.Join(Environment.NewLine, diagnostics.Select(x => x.ToString())));

        ResourceFieldDeclaration resource = PolarisResourceIndex.ForFile(inputPath).Find(document.CharacterResource)
            ?? throw new FormatException($"PNPC1001: CharacterResource '{document.CharacterResource}' was not found in this project.");
        if (!resource.DeclaringTypeHasFolderAttribute)
            throw new FormatException("PNPC1002: CharacterResource must belong to a type marked [PolarisResourceFolder].");
        if (!resource.IsStatic || !resource.IsAccessible)
            throw new FormatException("PNPC1003: CharacterResource must be an accessible static field.");
        if (!resource.IsTypeNamed("PxlsCharacterHandle"))
            throw new FormatException($"PNPC1004: CharacterResource must be PxlsCharacterHandle, not '{resource.SimpleTypeName}'.");

        string className = CSharpLiteral.SanitizeIdentifier(Path.GetFileNameWithoutExtension(inputPath));
        string ns = string.IsNullOrWhiteSpace(defaultNamespace) ? "Polaris.Generated" : defaultNamespace;
        string faction = Literal(document.Faction);
        string behavior = Literal(document.DefaultBehavior);

        return "// <auto-generated />\r\n" +
               "// Generated by PolarisPnpcGenerator from " + Path.GetFileName(inputPath) + ".\r\n\r\n" +
               "namespace " + ns + "\r\n{\r\n" +
               "    [global::Polaris.AI.Registration.PnpcAutoRegistration]\r\n" +
               "    internal sealed class " + className + "_PnpcRegistrar : global::Polaris.AI.Registration.IPnpcRegistrar\r\n" +
               "    {\r\n" +
               "        public void Register(global::Polaris.AI.Registration.PnpcRegistrationContext context)\r\n" +
               "        {\r\n" +
               "            context.Register(\r\n" +
               "                new global::Polaris.AI.Registration.PnpcDefinition(\r\n" +
               "                    \"" + CSharpLiteral.Escape(document.Id) + "\",\r\n" +
               "                    \"" + CSharpLiteral.Escape(document.InitialPose) + "\",\r\n" +
               "                    " + Float(document.Width) + ", " + Float(document.Height) + ", " + document.MaxHp + ", " + document.MaxMp + ",\r\n" +
               "                    global::Polaris.AI.Registration.PnpcHitType." + document.HitType + ", " + faction + ", " + behavior + "),\r\n" +
               "                () => global::" + resource.Reference + ");\r\n" +
               "        }\r\n" +
               "    }\r\n" +
               "}\r\n";
    }

    static string Float(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
    static string Literal(string? value) => value == null ? "null" : "\"" + CSharpLiteral.Escape(value) + "\"";
}
