using System.Globalization;
using System.Text;
using Polaris.Magic.Authoring;
using PolarisTools.Pui;

namespace PolarisTools.Magic.Generation;

/// <summary>
/// 从 <c>.pmagic</c> 文档发射 <c>.pmagic.g.cs</c> 的文本。
///
/// 生成物只有三样东西：带提供器特性的注册入口、魔法类那一半 partial（静态参数 + 回调工厂），
/// 以及一个把 code-behind 实例的 <c>RunAsync</c> 交出去的方法。这里没有图、没有阶段、
/// 没有逐 Tick 回调分派表——运行期行为完全由作者那一个 Task 决定。
///
/// 换行固定 CRLF，浮点用 R 格式并补 <c>f</c>，字符串走共享的 <see cref="CSharpLiteral.Escape"/>；
/// 同一份输入两次生成的字节必须完全相同，否则每次保存都会让 <c>.g.cs</c> 出现在源码控制的改动里。
/// </summary>
internal static class MagicCSharpEmitter
{
    /// <summary>生成的提供器类名后缀。</summary>
    internal const string ProviderSuffix = "__PolarisMagicProvider";

    /// <summary>生成的回调工厂方法名。带双下划线前缀，避免撞上作者自己的成员。</summary>
    internal const string CallbackFactoryName = "__CreateCallback";

    internal static string Emit(MagicDefinitionDocument document, string className, string namespaceName)
    {
        string providerName = className + ProviderSuffix;
        var text = new StringBuilder();

        text.Append("//------------------------------------------------------------------------------\r\n");
        text.Append("// <auto-generated>\r\n");
        text.Append("//     This file was generated by PolarisMagicGenerator from ").Append(className).Append(".pmagic.\r\n");
        text.Append("//     Edits are lost the next time the .pmagic file is saved.\r\n");
        text.Append("//     Write your magic logic in ").Append(className).Append(".pmagic.cs instead.\r\n");
        text.Append("// </auto-generated>\r\n");
        text.Append("//------------------------------------------------------------------------------\r\n");
        text.Append("\r\n");
        text.Append("using Polaris.Magic.Authoring;\r\n");
        text.Append("using Polaris.Magic.Definitions;\r\n");
        text.Append("using Polaris.Magic.Runtime;\r\n");
        text.Append("\r\n");
        text.Append("namespace ").Append(namespaceName).Append("\r\n");
        text.Append("{\r\n");

        EmitProvider(text, document, className, providerName);
        text.Append("\r\n");
        EmitMagicClass(text, document, className);

        text.Append("}\r\n");
        return text.ToString();
    }

    private static void EmitProvider(
        StringBuilder text,
        MagicDefinitionDocument document,
        string className,
        string providerName)
    {
        text.Append("    /// <summary>\r\n");
        text.Append("    /// PolarisMagic 的注册入口。启动时按特性扫描到它，调用 BuildDefinition 取定义——\r\n");
        text.Append("    /// 注册必须早于读档，因此不能等模组代码自己来调。\r\n");
        text.Append("    /// </summary>\r\n");
        text.Append("    [MagicDefinitionProvider]\r\n");
        text.Append("    internal sealed class ").Append(providerName).Append("\r\n");
        text.Append("    {\r\n");
        text.Append("        internal static MagicDefinition BuildDefinition()\r\n");
        text.Append("        {\r\n");
        text.Append("            var builder = new MagicDefinitionBuilder(").Append(className).Append(".Id);\r\n");
        text.Append("            builder.SetProviderAssembly(typeof(").Append(providerName).Append(").Assembly);\r\n");

        text.Append("            builder.SetCost(")
            .Append(Int(document.MpCost)).Append(", ")
            .Append(Float(document.CastTime)).Append(", ")
            .Append(Float(document.MpCrystalizeRatio)).Append(", ")
            .Append(Float(document.NeutralCrystalizeRatio)).Append(");\r\n");

        text.Append("            builder.SetTuning(")
            .Append(Float(document.PrepareTime)).Append(", ")
            .Append(Float(document.ManaDrainLock)).Append(", ")
            .Append(Int(document.ProjectilePower)).Append(", ")
            .Append(Float(document.ShotgunRatio)).Append(", ")
            .Append(Float(document.SuperArmorTiredTime)).Append(");\r\n");

        foreach (MagicCustomProperty property in document.Properties)
        {
            text.Append("            builder.AddProperty(\"").Append(CSharpLiteral.Escape(property.Name)).Append("\", ")
                .Append("MagicPropertyType.").Append(MagicPropertyValue.TypeToText(property.Type)).Append(", ")
                .Append(className).Append('.').Append(property.Name).Append(");\r\n");
        }

        text.Append("            builder.SetBehaviorFactory(").Append(className).Append('.')
            .Append(CallbackFactoryName).Append(");\r\n");
        text.Append("            return builder.Build();\r\n");
        text.Append("        }\r\n");
        text.Append("    }\r\n");
    }

    private static void EmitMagicClass(StringBuilder text, MagicDefinitionDocument document, string className)
    {
        text.Append("    public sealed partial class ").Append(className).Append("\r\n");
        text.Append("    {\r\n");
        text.Append("        /// <summary>稳定字符串 Id。存档里存的是 PolarisMagic 分配的数字 Id，不是这个字符串。</summary>\r\n");
        text.Append("        public const string Id = \"").Append(CSharpLiteral.Escape(document.Id)).Append("\";\r\n");
        text.Append("\r\n");

        EmitStatic(text, "int", "MpCost", Int(document.MpCost));
        EmitStatic(text, "float", "CastTime", Float(document.CastTime));
        EmitStatic(text, "float", "MpCrystalizeRatio", Float(document.MpCrystalizeRatio));
        EmitStatic(text, "float", "NeutralCrystalizeRatio", Float(document.NeutralCrystalizeRatio));
        EmitStatic(text, "float", "PrepareTime", Float(document.PrepareTime));
        EmitStatic(text, "float", "ManaDrainLock", Float(document.ManaDrainLock));
        EmitStatic(text, "int", "ProjectilePower", Int(document.ProjectilePower));
        EmitStatic(text, "float", "ShotgunRatio", Float(document.ShotgunRatio));
        EmitStatic(text, "float", "SuperArmorTiredTime", Float(document.SuperArmorTiredTime));

        foreach (MagicCustomProperty property in document.Properties)
        {
            EmitStatic(text, TypeKeyword(property.Type), property.Name, Literal(property));
        }

        text.Append("        /// <summary>\r\n");
        text.Append("        /// 每次正式施法造一个新的 code-behind 实例，并交出它那一个 RunAsync。\r\n");
        text.Append("        /// 工厂发射在这一半 partial 里而不是提供器类里：RunAsync 是私有成员，\r\n");
        text.Append("        /// 只有同一个类内部才拿得到它的方法组。\r\n");
        text.Append("        /// </summary>\r\n");
        text.Append("        internal static MagicTaskCallback ").Append(CallbackFactoryName).Append("() =>\r\n");
        text.Append("            new ").Append(className).Append("().").Append(MagicCodeBehindContract.RunMethodName)
            .Append(";\r\n");
        text.Append("    }\r\n");
    }

    private static void EmitStatic(StringBuilder text, string type, string name, string value)
    {
        text.Append("        public static ").Append(type).Append(' ').Append(name)
            .Append(" => ").Append(value).Append(";\r\n");
        text.Append("\r\n");
    }

    private static string TypeKeyword(MagicPropertyType type) => type switch
    {
        MagicPropertyType.Int => "int",
        MagicPropertyType.Float => "float",
        MagicPropertyType.Bool => "bool",
        _ => "string",
    };

    /// <summary>把一条自定义属性的文本值写成 C# 字面量。值的合法性已由共享校验保证。</summary>
    private static string Literal(MagicCustomProperty property)
    {
        switch (property.Type)
        {
            case MagicPropertyType.Int:
                MagicPropertyValue.TryParseInt(property.Value, out int intValue);
                return Int(intValue);

            case MagicPropertyType.Float:
                MagicPropertyValue.TryParseFloat(property.Value, out float floatValue);
                return Float(floatValue);

            case MagicPropertyType.Bool:
                MagicPropertyValue.TryParseBool(property.Value, out bool boolValue);
                return boolValue ? "true" : "false";

            default:
                return "\"" + CSharpLiteral.Escape(property.Value) + "\"";
        }
    }

    private static string Int(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>R 格式保证往返一致；补 <c>f</c> 让它是 float 而不是 double 字面量。</summary>
    private static string Float(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
}
