using System;
using System.Globalization;
using System.Text;
using Polaris.Addons.Authoring;
using PolarisTools.Pui;

namespace PolarisTools.Addons.Generation;

internal static class AddonCSharpEmitter
{
    internal static string Emit(
        AddonDefinitionDocument document,
        string className,
        string namespaceName,
        string sourceExtension)
    {
        var text = new StringBuilder();
        Header(text, className, sourceExtension);
        text.Append("using System;\r\n");
        text.Append("using Polaris.Addons.Authoring;\r\n");
        text.Append("using Polaris.Addons.Definitions;\r\n\r\n");
        text.Append("namespace ").Append(namespaceName).Append("\r\n{\r\n");

        switch (document)
        {
            case ItemDefinitionDocument item:
                EmitItem(text, item, className);
                break;
            case PluginDefinitionDocument plugin:
                EmitPlugin(text, plugin, className);
                break;
            case SkillDefinitionDocument skill:
                EmitSkill(text, skill, className);
                break;
            default:
                throw new AddonFormatException("Unsupported Addons document type.");
        }

        text.Append("}\r\n");
        return text.ToString();
    }

    private static void Header(StringBuilder text, string className, string extension)
    {
        text.Append("//------------------------------------------------------------------------------\r\n");
        text.Append("// <auto-generated>\r\n");
        text.Append("//     Generated by PolarisTools from ").Append(className).Append(extension).Append(".\r\n");
        text.Append("//     Edit the source document, not this file.\r\n");
        text.Append("// </auto-generated>\r\n");
        text.Append("//------------------------------------------------------------------------------\r\n\r\n");
    }

    private static void EmitItem(StringBuilder text, ItemDefinitionDocument item, string className)
    {
        string provider = className + "__PolarisItemProvider";
        text.Append("    [ItemDefinitionProvider]\r\n");
        text.Append("    internal sealed class ").Append(provider).Append("\r\n    {\r\n");
        text.Append("        internal static ItemDefinition BuildDefinition()\r\n        {\r\n");
        text.Append("            var builder = new ItemDefinitionBuilder(\"").Append(Escape(item.Id)).Append("\");\r\n");
        text.Append("            builder.SetProviderAssembly(typeof(").Append(provider).Append(").Assembly);\r\n");
        text.Append("            builder.SetPresentation(\"").Append(Escape(item.NameKey)).Append("\", \"")
            .Append(Escape(item.DescriptionKey)).Append("\", \"").Append(Escape(item.Icon)).Append("\");\r\n");
        text.Append("            builder.SetInventory(").Append(item.Price.ToString(CultureInfo.InvariantCulture)).Append(", ")
            .Append(item.StackLimit.ToString(CultureInfo.InvariantCulture)).Append(", \"")
            .Append(Escape(item.Category)).Append("\");\r\n");
        Behavior(text, item.BehaviorType);
        text.Append("            return builder.Build();\r\n        }\r\n    }\r\n\r\n");
        IdClass(text, className, item.Id);
    }

    private static void EmitPlugin(StringBuilder text, PluginDefinitionDocument plugin, string className)
    {
        string provider = className + "__PolarisPluginProvider";
        text.Append("    [PluginDefinitionProvider]\r\n");
        text.Append("    internal sealed class ").Append(provider).Append("\r\n    {\r\n");
        text.Append("        internal static PluginDefinition BuildDefinition()\r\n        {\r\n");
        text.Append("            var builder = new PluginDefinitionBuilder(\"").Append(Escape(plugin.Id)).Append("\");\r\n");
        text.Append("            builder.SetProviderAssembly(typeof(").Append(provider).Append(").Assembly);\r\n");
        text.Append("            builder.SetOwnerItem(\"").Append(Escape(plugin.ItemId)).Append("\");\r\n");
        text.Append("            builder.SetPresentation(\"").Append(Escape(plugin.TitleKey)).Append("\", \"")
            .Append(Escape(plugin.DescriptionKey)).Append("\", \"").Append(Escape(plugin.Icon)).Append("\");\r\n");
        text.Append("            builder.SetCost(").Append(plugin.Cost.ToString(CultureInfo.InvariantCulture)).Append(");\r\n");
        Behavior(text, plugin.BehaviorType);
        text.Append("            return builder.Build();\r\n        }\r\n    }\r\n\r\n");
        IdClass(text, className, plugin.Id);
    }

    private static void EmitSkill(StringBuilder text, SkillDefinitionDocument skill, string className)
    {
        string provider = className + "__PolarisSkillProvider";
        text.Append("    [SkillDefinitionProvider]\r\n");
        text.Append("    internal sealed class ").Append(provider).Append("\r\n    {\r\n");
        text.Append("        internal static SkillDefinition BuildDefinition()\r\n        {\r\n");
        text.Append("            var builder = new SkillDefinitionBuilder(\"").Append(Escape(skill.Id)).Append("\");\r\n");
        text.Append("            builder.SetProviderAssembly(typeof(").Append(provider).Append(").Assembly);\r\n");
        text.Append("            builder.SetOwnerItem(\"").Append(Escape(skill.ItemId)).Append("\");\r\n");
        text.Append("            builder.SetPresentation(\"").Append(Escape(skill.TitleKey)).Append("\", \"")
            .Append(Escape(skill.DescriptionKey)).Append("\", \"").Append(Escape(skill.Icon)).Append("\");\r\n");
        text.Append("            builder.SetPolicy(AddonSkillMode.").Append(skill.Mode)
            .Append(", AddonSkillUnlockPolicy.").Append(skill.Unlock).Append(");\r\n");
        text.Append("            builder.SetExecutionPolicy(")
            .Append(skill.CooldownSeconds.ToString("R", CultureInfo.InvariantCulture)).Append("d, \"")
            .Append(Escape(skill.ConcurrencyGroup)).Append("\");\r\n");
        Behavior(text, skill.BehaviorType);
        text.Append("            return builder.Build();\r\n        }\r\n    }\r\n\r\n");
        IdClass(text, className, skill.Id);
    }

    private static void Behavior(StringBuilder text, string behaviorType)
    {
        if (!string.IsNullOrWhiteSpace(behaviorType))
        {
            string typeName = behaviorType.Trim();
            if (!typeName.StartsWith("global::", StringComparison.Ordinal))
            {
                typeName = "global::" + typeName;
            }

            text.Append("            builder.SetBehavior(typeof(").Append(typeName).Append("));\r\n");
        }
    }

    private static void IdClass(StringBuilder text, string className, string id)
    {
        text.Append("    public static class ").Append(className).Append("\r\n    {\r\n");
        text.Append("        public const string Id = \"").Append(Escape(id)).Append("\";\r\n");
        text.Append("    }\r\n");
    }

    private static string Escape(string value) => CSharpLiteral.Escape(value ?? string.Empty);
}
